### PR TITLE
Add `total` to TasksResult

### LINKED ISSUE #402: [v1.3] Total Tasks in task route
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

### New implementation

Related to:
- spec: https://github.com/meilisearch/specifications/pull/253

Returns the total number of tasks matching the filters on the `GET /tasks` route.

Ensure the SDKs can handle the new get tasks response field `total`

TODO:
- [ ] Handle the response of the `getTasks` method by including the new attribute `total`

### PR DESCRIPTION
**Pull request by Sherlouk**
# Pull Request

## Related issue
Fixes #402

## What does this PR do?
- Adds support for new `total` attribute to GET tasks request. This is a recent addition, and so it may be desired to make this optional for backwards compatibility.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @Sherlouk 
Thank you for your PR

Looks like the CI is failing, can you fix the test?

```
 Test Case 'IndexesTests.testGetTasksWithParametersFromIndex' started at 2023-09-21 17:26:55.334
▿ Swift.DecodingError.keyNotFound
  ▿ keyNotFound: (2 elements)
    - .0: CodingKeys(stringValue: "total", intValue: nil)
    ▿ .1: Swift.DecodingError.Context
      - codingPath: 0 elements
      - debugDescription: "No value associated with key CodingKeys(stringValue: \"total\", intValue: nil) (\"total\")."
      - underlyingError: nil
```

Here is the CI so that you can see the full logs: https://github.com/meilisearch/meilisearch-swift/actions/runs/6213141814/job/17012982161?pr=412

**Comment by Sherlouk** [comment]
Well I'm glad that it turned out that I was just being a bit silly and only ran the integration tests, as they're separate within Xcode! The unit tests have embedded JSON, not relying on the running of a local Meili instance. 

I've updated, and run all tests this time, and am confident I've patched that now.

I've also familiarised myself with the GitHub Actions workflows so am more confident in what that does.

**Comment by Sherlouk** [comment]
Can see [here](https://github.com/meilisearch/meilisearch-swift/actions/runs/6267733199/job/17021350022) that I was running into some random errors trying to download MeiliSearch itself - retrying resolved it (but explains the empty force commits).

**Comment by Sherlouk** [comment]
I'm going to close this PR as once #417 is merged I have a PR which covers the rest of task parity (and for the sake of 7 lines of code makes sense to include there).

**Pull request closed without merging**
