### PR TITLE
Fix batch delete for string document ids. (#330)

### LINKED ISSUE #330: Batch delete expects an array of Int for document id (even though string document ids are also valid)
**Description**
Batch deletion from index expects an array of int for document ID even though said ID can be any valid String, such as a UUID for example.

**Expected behavior**
Batch deletion should work similar to single deletion - it should accept strings of any kind.

**Environment (please complete the following information):**
- OS: Ubuntu 22.04
- Meilisearch version: 0.28
- meilisearch-swift version: 0.14.1

### PR DESCRIPTION
**Pull request by aronbudinszky**
# Pull Request

## What does this PR do?
Fixes #330

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by brunoocasali — COMMENTED** [review]
Hi @aronbudinszky, thanks for one more contribution to Meilisearch ❤️ 

I'm willing to merge your PR, but I would like to avoid breaking for the users currently calling the method with integers.

Do you have any idea whether to accept both types at the same type? Or even create a new method for that?

**Comment by aronbudinszky** [comment]
Oh very good point!

Will update that tomorrow by adding a bridging method along with a deprecation notice.

**Comment by aronbudinszky** [comment]
Hi @brunoocasali!

I readded the [Int] methods along with unit tests. Since using Int ids is "wrong" I've also added a deprecation notice so that people who use the old method will get notified to change to string values.

**Review by brunoocasali — APPROVED** [review]
Amazing job @aronbudinszky ❤️ 

bors merge

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
bors merge

**Comment by curquiza** [comment]
I've opened a PR to fix this bors issue 😇 
https://github.com/meilisearch/meilisearch-swift/pull/333

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
