### PR TITLE
Update version for the next release (v0.13.2)

### PR DESCRIPTION
**Pull request by bidoubiwa**
This version makes this package compatible with Meilisearch v0.27.0 :tada:
Check out the changelog of [Meilisearch v0.27.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0) for more information on the changes.

## 🚀 Enhancements

* Add new search parameters highlightPreTag, highlightPostTag and cropMarker (#288) @bidoubiwa
* Ensure nested fields support (#287)
 @bidoubiwa

Thanks again to @bidoubiwa 🎉

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]

**Comment by bidoubiwa** [comment]
closed in favor of #294

**Review by brunoocasali — DISMISSED** [review]
LGTM!

**Review by brunoocasali — DISMISSED** [review]

**Review by brunoocasali — APPROVED** [review]
👍 LGTM!

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
