### PR TITLE
[#77] Add SwiftLint job for test workflow

### PR DESCRIPTION
**Pull request by Ethenyl**
# Summary

Add a **SwiftLint** step into jobs which are including tests.

# Miscellaneous

Implements #77.
Removed deprecated SwiftLint rules & added a rule for line length.

### CODE REVIEW

**Review by ppamorim — APPROVED** [review]

**Comment by Ethenyl** [comment]
I had to merge your `master` into my own, hence the review reset.

**Review by ppamorim — APPROVED** [review]

**Comment by ppamorim** [comment]
@Ethenyl Thank you again, I requested the review from @curquiza.

**Comment by Ethenyl** [comment]
@ppamorim you're welcome 😉 I will check the other issues when I have some free time.

**Review by curquiza — APPROVED** [review]
Really nice!! 😁

**Comment by curquiza** [comment]
Thank you @Ethenyl for your work, and @ppamorim for your review!
bors merge

**Pull request merged**
