### PR TITLE
Fix typo in README.md

### LINKED ISSUE #350: Typo Fix in README.md
There's a typo in the README.md, I would like to fix it. I'll also link a PR with this issue. 
The typo is with the Getting Started section in the README.md. 
MISTAKE :- 
To do a simply search using the client, you can create a Swift script like this:
FIX :- 
To do a simple search using the client, you can create a Swift script like this:

Screenshot 2022-10-31 at 9 11 55 PM

### PR DESCRIPTION
**Pull request by Dishant10**
# Pull Request

## Related issue
Fixes #350 

## What does this PR do?
Fixes a typo in readme.md file. 

## PR checklist
Please check if your PR fulfills the following requirements:
- [ • ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ • ] Have you read the contributing guidelines?
- [ • ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by Dishant10** [comment]
Made all the necessary changes to the README.md file.

**Review by brunoocasali — APPROVED** [review]
Thank you @Dishant10 

bors merge

**Comment by brunoocasali** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by Dishant10** [comment]
Thank you! @brunoocasali 
I would love to contribute more to this project. I'm looking at some open issues. If you have something in mind that I can do, please let me know.

**Comment by brunoocasali** [comment]
Fantastic to hear that @Dishant10 if you want you can check the issues there is always something to be fixed that is already described there.

If you want some recommendations: #341 and #343 that could be your starting point :)

**Pull request merged**
