### PR TITLE
Run autocorrect with swiftlint

### PR DESCRIPTION
**Pull request by brunoocasali**
Related to https://github.com/meilisearch/meilisearch-swift/issues/235

All changes were made automatically by swiftlint.

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Thanks @brunoocasali 🔥 Could you add the command you used into the `CONTRIBUTING.md` ?

**Comment by brunoocasali** [comment]
> Thanks @brunoocasali 🔥 Could you add the command you used into the `CONTRIBUTING.md` ?

Actually, It won’t be necessary :)

https://github.com/meilisearch/meilisearch-swift/pull/236/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L53

I've added a little more information about the configuration (link above), but I renamed the current swiftlint policy to the new one, so in this case, when we run the lint we will run the new config as well.

**Comment by bidoubiwa** [comment]
Hello @brunoocasali 
Since our tests are flacky I can't confirm they are actually working.  Nonetheless since all you do is lining I assume they do not break tests. Did you try the tests locally?

**Comment by brunoocasali** [comment]
> Hello @brunoocasali Since our tests are flacky I can't confirm they are actually working. Nonetheless since all you do is lining I assume they do not break tests. Did you try the tests locally?

Yes, I did and they all pass, but if we merge it, probably we will break the main branch, right?

**Comment by bidoubiwa** [comment]
> Yes, I did and they all pass, but if we merge it, probably we will break the main branch, right?


Sorry for the delay. If the tests pass locally it will not break the main branch. The failing test are due to a problem downloading the meilisearch binary in the mac-os environment of this CI. 
We are not sure why :s

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥 Thanks so much for this PR 

Is it ready to be merged for you?

**Comment by bidoubiwa** [comment]
bors try

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
