### PR TITLE
Add bors config

### PR DESCRIPTION
**Pull request by bidoubiwa**
Add bors plugin on this repository.

This will helps test, merge and rebase.

### CODE REVIEW

**Comment by MarinPostma** [comment]
bors try

**Comment by bidoubiwa** [comment]
bors try

**Comment by bidoubiwa** [comment]
Any idea why the tests pass or github actions but not on bors w/ github actions ? @curquiza @ppamorim

**Comment by bidoubiwa** [comment]
bors try

**Comment by ppamorim** [comment]
@bidoubiwa did it work now? hehe

**Comment by bidoubiwa** [comment]
Yes haha.. I think I fixed it in another PR. In any case I think we should add a sleep before the call in `testDeleteAllDocuments`.

**Review by curquiza — APPROVED** [review]
I will put the `hacktoberfest` label for you @bidoubiwa 😘

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
