### PR TITLE
Fix test command in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Any idea why the tests might be failing?

**Comment by curquiza** [comment]
Yes, because the script used in the CI download the latest release and not the latest stable one :(
https://github.com/meilisearch/meilisearch-swift/blob/main/.github/scripts/latest_release_meilisearch.sh

**Comment by curquiza** [comment]
[A PR on core side](https://github.com/meilisearch/MeiliSearch/pull/1760) from a contributor will let us use the [`download-latest.sh` script](https://github.com/meilisearch/MeiliSearch/blob/main/download-latest.sh) in the CI instead of the one in this repo.

**Comment by curquiza** [comment]
I think we can merge this PR wihout bors exceptionally since we are sure it does not impact the code base but only the documentation

**Review by bidoubiwa — APPROVED** [review]

**Pull request merged**
