### PR TITLE
Fix: remove charset=utf-8 from Content-Type header

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Review by bidoubiwa — COMMENTED** [review]
I see you didn't setValue for the `get` method. Is there a reason?

**Comment by curquiza** [comment]
> I see you didn't setValue for the get method. Is there a reason?

Which part do you mean? There is no `setValue` regarding the content type for the `get` method, right?

**Comment by bidoubiwa** [comment]
Ah yes, my bad!

**Review by bidoubiwa — APPROVED** [review]
bors merge

**Pull request merged**
