### PR TITLE
Change search method from get to post

### PR DESCRIPTION
**Pull request by bidoubiwa**
Not correctly tested yet but this will come in a later PR.

fixes: #26

### CODE REVIEW

**Review by ppamorim — DISMISSED** [review]

**Comment by curquiza** [comment]
Are these changes breaking @bidoubiwa?

**Comment by bidoubiwa** [comment]
I will merge once I have made another PR changing the tests

**Comment by ppamorim** [comment]
@bidoubiwa Can I rebase this?

**Comment by curquiza** [comment]
Hello @ppamorim, since it's the branch and work of @bidoubiwa, do **not** rebase her branch 😉 It would fuck up her local repository because you would change the remote history.
We want to keep simple rule with git: a branch per issue and only one developer on one branch 🙂

**Review by curquiza — APPROVED** [review]

**Comment by ppamorim** [comment]
@bidoubiwa Thank you very much.

**Review by ppamorim — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
