### PR TITLE
Add Linux support (#245)

### PR DESCRIPTION
**Pull request by bidoubiwa**
Origin #245 
fixes: #1 

TODO:

- [x] Add linux environment in the CI

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Is it possible to run the tests against a linux env the same way we do with the mac env?

**Comment by brunoocasali** [comment]
> Is it possible to run the tests against a linux env the same way we do with the mac env?

Yes I think so, I'll add this as a new requirement to merge this PR, thanks!

**Comment by bidoubiwa** [comment]
LGTM 🔥

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
