### PR TITLE
Remove SQLite warnings in integration tests

### LINKED ISSUE #139: Remove SQLITE_FILEPROTECTION warning on tests run
**Description**
When tests are runned, warning are spammed: 

```
[logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags\
```

**Expected behavior**
Avoid warning spamming the console and making errors hard to spot.

**Current behavior**

A lot of the following warning:
```
[logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags\
```

**Possible solutions**

This [stackoverflow](https://stackoverflow.com/questions/65279008/swiftui-macos-fetch-json-error-logging-volume-does-not-support-data-protection)

### PR DESCRIPTION
**Pull request by curquiza**
Follows #221 

Fixes #139

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
bors try

**Review by bidoubiwa — APPROVED** [review]
🥲 LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
